### ISSUE TITLE
Ability to zoom out on canvases 

### ISSUE THREAD

**Issue by rphacks** [streamr-dev/streamr-platform#445]
**Is your feature request related to a problem? Please describe.**
Sometimes one or two modules take up most of the visible canvas. 

**Describe the solution you'd like**
The ability to zoom out of a canvas please. 

**Additional context**
Example:
![image](https://user-images.githubusercontent.com/43719022/57879190-bd784b80-7813-11e9-909e-5ce084c20259.png)

**Comment by fonty1** [comment]
Hey @rphacks - Thanks for the feature request. A fix is indeed warranted here. 

What's been discussed is a 'Zoom and Pan' feature which will help users traverse the Canvas like a map. This should be a good fit for this problem as you suggest. 

It's on our product backlog - I'll let you know when it gets merged.

**Comment by fonty1** [comment]
@rphacks the ability to zoom in/out of canvases is now live. Pls check it out!

https://streamr.network/canvas/editor
