### ISSUE TITLE
MetaMask browser extension is locked

### ISSUE THREAD

**Issue by remykonings** [streamr-dev/streamr-platform#452]
It seems that login with Ethereum throught Metamask is not working. 
It gives me the error that" MetaMask browser extension is locked" while it is open.

**App version**
Streamr App v2.0.5-456-G7E20DD2

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave
 - Version 0.63.55 Chromium: 74.0.3729.131 (Official Build) (64-bit)

![2019-05-17 16_19_18-Streamr Marketplace - Brave](https://user-images.githubusercontent.com/6934783/57934832-c541f980-78c0-11e9-84bf-447233af8bce.png)

**Comment by fonty1** [comment]
Thanks @remykonings - This is due to the new Metamask privacy settings and we're in the middle of fixing it ASAP! 

Will let you know when its solved and deployed 💪

**Comment by fonty1** [comment]
@remykonings the fix has been merged and you can try it out here:
[streamr.com/login](streamr.com/login)
