### ISSUE TITLE
Show expiration date of a bought stream in the product overview page

### ISSUE THREAD

**Issue by remykonings** [streamr-dev/streamr-platform#504]
Currently when you buy a stream, the button changes from a "purchase" to a "renew" function.

It would be great if there could be a spot in the product overview page (e.g. in the button itself) where it will show the user the remaining time that the stream is still be available.

This countdown will also be great to see in the "Purchases" tab.

![Screen Shot 2019-05-30 at 16 30 00](https://user-images.githubusercontent.com/6934783/58641221-14455100-82fb-11e9-8356-26d54e9fcf1e.png)

**Comment by fonty1** [comment]
Good idea @remykonings! We discussed this, this morning - it seemed trivial to implement and a desired feature so it's been added to our backlog 👍

**Comment by mattatgit** [comment]
This one got lost because not on Jira as an active ticket, so am closing this, but have created a Jira ticket for it, we have already done the design work.
